prettyPrint: true
cacheTTL: 0
resourceClasses:
  - edu.pdx.cs410J.whitlock.PhoneBillRestApi
openAPI:
  info:
    version: 'Summer2020'
    title: 'RestEasy, Guice, and Swagger.  Oh my!'
  servers:
    - url: '/phonebill'